#!/bin/bash
#SBATCH --nodes=1               # number of nodes
#SBATCH --ntasks-per-node=4     # number of tasks per node
#SBATCH --ntasks-per-socket=2   # number of tasks per socket
#SBATCH --cpus-per-task=32      # number of HW threads per task (equal to OMP_NUM_THREADS*4)
#SBATCH --gres=gpu:4            # this refers to the number of requested gpus per node, and can vary between 1 and 4
#SBATCH --mem=230000MB
#SBATCH --time 00:03:00         # format: HH:MM:SS
#SBATCH -A cin_extern02
#SBATCH -p m100_usr_prod
#SBATCH --job-name "cans"
#SBATCH --output=output_test.%j.out

module load hpc-sdk/2020--binary python cuda/10.2 fftw

PARAVIEW_ROOT=${HOME}/libraries/paraview-5.8.1
export PV_PLUGIN_PATH=${PARAVIEW_ROOT}/lib64/paraview-5.8/plugins/

mpirun -np 1 --bind-to none ./run_cans
