name: compilation test

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install software
      run: |
        sudo apt-get update; sudo apt-get install gfortran libopenmpi-dev libfftw3-dev
        #
        NVVERSION_A=20.11
        NVVERSION_B=2011
        CUDA_VERSION=11.1
        export NVHPC_SILENT=true
        export NVHPC_INSTALL_TYPE=single
        export NVHPC_INSTALL_DIR=$HOME/software/nvidia/hpc_sdk
        wget https://developer.download.nvidia.com/hpc-sdk/$NVVERSION_A/nvhpc_2020_${NVVERSION_B}_Linux_x86_64_cuda_$CUDA_VERSION.tar.gz
        tar xpzf nvhpc_2020_${NVVERSION_B}_Linux_x86_64_cuda_$CUDA_VERSION.tar.gz
        ./nvhpc_2020_${NVVERSION_B}_Linux_x86_64_cuda_$CUDA_VERSION/install
        rm -rf nvhpc_2020_${NVVERSION_B}_Linux_x86_64_cuda_$CUDA_VERSION*
    - name: test compilation
      run: |
        NVVERSION=20.11
        NVHPC_INSTALL_DIR=$HOME/software/nvidia/hpc_sdk
        NVARCH=`uname -s`_`uname -m`; export NVARCH
        NVCOMPILERS=$NVHPC_INSTALL_DIR; export NVCOMPILERS
        MANPATH=$MANPATH:$NVCOMPILERS/$NVARCH/$NVVERSION/compilers/man; export MANPATH
        PATH=$NVCOMPILERS/$NVARCH/$NVVERSION/compilers/bin:$PATH; export PATH
        export PATH=$NVCOMPILERS/$NVARCH/$NVVERSION/comm_libs/mpi/bin:$PATH
        export MANPATH=$MANPATH:$NVCOMPILERS/$NVARCH/$NVVERSION/comm_libs/mpi/man
        export LD_LIBRARY_PATH=$NVHPC_INSTALL_DIR/Linux_x86_64/$NVVERSION/compilers/lib:$LD_LIBRARY_PATH
        #
        cd src/
        make -j                            && make run && make clean
        make -j OPT=-O3 OTH=               && make run && make clean
        make -j OPT=-O3 OTH= OMP+=-fopenmp && make run && make clean
